Task-1

In [1]:
import sqlite3
conn=sqlite3.connect("bookstore.db")
cursor=conn.cursor()
cursor.execute("""
   CREATE TABLE IF NOT EXISTS books (
      book_id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT NOT NULL,
      author TEXT NOT NULL,
      price REAL NOT NULL,
      stock_quantity INTEGER DEFAULT 0)"""
)
cursor.execute("""
  CREATE TABLE IF NOT EXISTS customers (
      customer_id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      email TEXT NOT NULL,
      city TEXT,
      join_date TEXT)"""
)
cursor.execute("""
CREATE TABLE IF NOT EXISTS orders (
    order_id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER,
    book_id INTEGER,
    quantity INTEGER NOT NULL,
    order_date TEXT NOT NULL,
    total_amount REAL NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (book_id) REFERENCES books(book_id)
    )
""")

In [2]:
cursor.execute("PRAGMA table_info(books)")
books_table_info=cursor.fetchall()
for column in books_table_info:
  print(column)

(0, 'book_id', 'INTEGER', 0, None, 1)
(1, 'title', 'TEXT', 1, None, 0)
(2, 'author', 'TEXT', 1, None, 0)
(3, 'price', 'REAL', 1, None, 0)
(4, 'stock_quantity', 'INTEGER', 0, '0', 0)

In [3]:
cursor.execute("PRAGMA table_info(customers)")
customers_table_info=cursor.fetchall()
for column in customers_table_info:
  print(column)

(0, 'customer_id', 'INTEGER', 0, None, 1)
(1, 'name', 'TEXT', 1, None, 0)
(2, 'email', 'TEXT', 1, None, 0)
(3, 'city', 'TEXT', 0, None, 0)
(4, 'join_date', 'TEXT', 0, None, 0)

In [4]:
cursor.execute("PRAGMA table_info(orders)")
orders_table_info=cursor.fetchall()
for column in orders_table_info:
  print(column)

(0, 'order_id', 'INTEGER', 0, None, 1)
(1, 'customer_id', 'INTEGER', 0, None, 0)
(2, 'book_id', 'INTEGER', 0, None, 0)
(3, 'quantity', 'INTEGER', 1, None, 0)
(4, 'order_date', 'TEXT', 1, None, 0)
(5, 'total_amount', 'REAL', 1, None, 0)

Task-2 Part-A

In [5]:
books_data = [
      ('Python Programming', 'John Smith', 599.99, 25),
      ('Data Science Handbook', 'Jane Doe', 899.50, 15),
      ('Machine Learning Basics', 'Alan Turing', 1299.00, 10),
      ('SQL Essentials', 'Edgar Codd', 499.99, 30),
      ('Web Development', 'Tim Berners', 799.00, 20)
]

customers_data = [
      ('Rahul Sharma', 'rahul@email.com', 'Mumbai', '2024-01-15'),
      ('Priya Patel', 'priya@email.com', 'Delhi', '2024-01-20'),
      ('Amit Kumar', 'amit@email.com', 'Bangalore', '2024-02-01'),
      ('Sneha Reddy', 'sneha@email.com', 'Hyderabad', '2024-02-10'),
      ('Vikram Singh', 'vikram@email.com', 'Mumbai', '2024-02-15')
 ]

orders_data = [
      (1, 1, 2, '2024-03-01', 1199.00),
      (1, 2, 1, '2024-03-02', 899.50),
      (2, 1, 1, '2024-03-03', 599.99),
      (2, 3, 1, '2024-03-05', 1299.00),
      (3, 4, 3, '2024-03-07', 1499.97),
      (4, 2, 1, '2024-03-10', 899.50),
      (5, 5, 2, '2024-03-12', 1598.00)
]

cursor.executemany("insert into books('title','author',price,stock_quantity) values(?,?,?,?)",books_data)
cursor.executemany("insert into customers('name','email','city','join_date') values(?,?,?,?)",customers_data)
cursor.executemany("insert into orders('customer_id','book_id',quantity,'order_date',total_amount) values(?,?,?,?,?)",orders_data)
conn.commit()

In [6]:
cursor.execute("select * from books")
row=cursor.fetchall()
for rows in row:
  print(rows)

(1, 'Python Programming', 'John Smith', 599.99, 25)
(2, 'Data Science Handbook', 'Jane Doe', 899.5, 15)
(3, 'Machine Learning Basics', 'Alan Turing', 1299.0, 10)
(4, 'SQL Essentials', 'Edgar Codd', 499.99, 30)
(5, 'Web Development', 'Tim Berners', 799.0, 20)

In [7]:
cursor.execute("select * from customers")
row=cursor.fetchall()
for rows in row:
  print(rows)

(1, 'Rahul Sharma', 'rahul@email.com', 'Mumbai', '2024-01-15')
(2, 'Priya Patel', 'priya@email.com', 'Delhi', '2024-01-20')
(3, 'Amit Kumar', 'amit@email.com', 'Bangalore', '2024-02-01')
(4, 'Sneha Reddy', 'sneha@email.com', 'Hyderabad', '2024-02-10')
(5, 'Vikram Singh', 'vikram@email.com', 'Mumbai', '2024-02-15')

In [8]:
cursor.execute("select * from orders")
row=cursor.fetchall()
for rows in row:
  print(rows)

(1, 1, 1, 2, '2024-03-01', 1199.0)
(2, 1, 2, 1, '2024-03-02', 899.5)
(3, 2, 1, 1, '2024-03-03', 599.99)
(4, 2, 3, 1, '2024-03-05', 1299.0)
(5, 3, 4, 3, '2024-03-07', 1499.97)
(6, 4, 2, 1, '2024-03-10', 899.5)
(7, 5, 5, 2, '2024-03-12', 1598.0)

Task-2 Part-B

In [9]:
cursor.execute("select * from customers where city='Mumbai'")
row=cursor.fetchall()
for rows in row:
  print(rows)

(1, 'Rahul Sharma', 'rahul@email.com', 'Mumbai', '2024-01-15')
(5, 'Vikram Singh', 'vikram@email.com', 'Mumbai', '2024-02-15')

In [10]:
cursor.execute("select * from books where price>800 and stock_quantity>10")
row=cursor.fetchall()
for rows in row:
  print(rows)

(2, 'Data Science Handbook', 'Jane Doe', 899.5, 15)

In [11]:
cursor.execute("select count(*) from orders")
row=cursor.fetchone()
print(row)

(7,)

In [12]:
cursor.execute("select customer_id,count(*) from orders GROUP BY customer_id ORDER BY count(*) DESC ")
row=cursor.fetchall()
for rows in row:
  print(rows)

(2, 2)
(1, 2)
(5, 1)
(4, 1)
(3, 1)

In [13]:
cursor.execute("SELECT SUM(total_amount) FROM ORDERS")
row=cursor.fetchone()
print(row)

(7994.96,)

In [14]:
import pandas as pd
books=pd.read_sql("SELECT * FROM BOOKS",conn)
customers=pd.read_sql("SELECT * FROM CUSTOMERS",conn)
orders=pd.read_sql("SELECT * FROM ORDERS",conn)

In [15]:
print(books.head(3))
print(customers.head(3))
print(orders.head(3))

   book_id                    title       author    price  stock_quantity
0        1       Python Programming   John Smith   599.99              25
1        2    Data Science Handbook     Jane Doe   899.50              15
2        3  Machine Learning Basics  Alan Turing  1299.00              10
   customer_id          name            email       city   join_date
0            1  Rahul Sharma  rahul@email.com     Mumbai  2024-01-15
1            2   Priya Patel  priya@email.com      Delhi  2024-01-20
2            3    Amit Kumar   amit@email.com  Bangalore  2024-02-01
   order_id  customer_id  book_id  quantity  order_date  total_amount
0         1            1        1         2  2024-03-01       1199.00
1         2            1        2         1  2024-03-02        899.50
2         3            2        1         1  2024-03-03        599.99

In [16]:
report=pd.merge(orders,customers,on='customer_id')
finalreport=pd.merge(report,books,on='book_id')
finalreport[['order_id','name','city','title','quantity','total_amount']]

,order_id,name,city,title,quantity,total_amount
0,1,Rahul Sharma,Mumbai,Python Programming,2,1199.00
1,2,Rahul Sharma,Mumbai,Data Science Handbook,1,899.50
2,3,Priya Patel,Delhi,Python Programming,1,599.99
3,4,Priya Patel,Delhi,Machine Learning Basics,1,1299.00
4,5,Amit Kumar,Bangalore,SQL Essentials,3,1499.97
5,6,Sneha Reddy,Hyderabad,Data Science Handbook,1,899.50
6,7,Vikram Singh,Mumbai,Web Development,2,1598.00

In [17]:
print(finalreport['total_amount'].mean())

1142.1371428571429

In [18]:
finalreport.groupby('city')['order_id'].count()

city
Bangalore    1
Delhi        2
Hyderabad    1
Mumbai       3
Name: order_id, dtype: int64

In [19]:
finalreport.groupby('title')['quantity'].max().sort_values(ascending=False).head(1)

title
SQL Essentials    3
Name: quantity, dtype: int64

Task-3 Part-B

In [20]:
discounts_data = {
      'book_id': [1, 2, 3, 4, 5],
       'discount_percent': [10, 15, 5, 20, 12]
}
discounts=pd.DataFrame(discounts_data)
discounts.to_sql('discounts',conn,if_exists='replace',index=False)

5

In [21]:
cursor.execute("select * from discounts")
row=cursor.fetchall()
for rows in row:
  print(rows)

(1, 10)
(2, 15)
(3, 5)
(4, 20)
(5, 12)

In [22]:
cursor.execute("""
SELECT books.title,
       books.price,
       discounts.discount_percent,
       books.price - (books.price * discounts.discount_percent / 100) AS discounted_price
       FROM books
       INNER JOIN discounts
       ON books.book_id = discounts.book_id
 """)

rows = cursor.fetchall()

for row in rows:
      print(row)
conn.close()

('Python Programming', 599.99, 10, 539.991)
('Data Science Handbook', 899.5, 15, 764.575)
('Machine Learning Basics', 1299.0, 5, 1234.05)
('SQL Essentials', 499.99, 20, 399.992)
('Web Development', 799.0, 12, 703.12)