Dataframe Creation

In [8]:
import pandas as pd
import pandas as pd
data={
    "Employee_ID":[201,202,203,204,205,206,207,208,209,210],
     "Name":["Sarah","Michael","Jennifier","David","Lisa","james","Emma","Robert","Sophia","William"],
     "Department":["Engineering","sales","Marketing","Engineering","HR","Sales","Engineering","Marketing","Sales","HR"],
     "Salary":[85000,62000,71000,92000,58000,68000,78000,75000,65000,60000],
     "Perfomancescore":[4,3,5,5,4,4,3,4,5,3],
     "Yearofservice":[5,3,7,8,4,6,2,5,4,3]
                        }
df=pd.DataFrame(data)
df

   Employee_ID       Name   Department  Salary  Perfomancescore  Yearofservice
0          201      Sarah  Engineering   85000                4              5
1          202    Michael        sales   62000                3              3
2          203  Jennifier    Marketing   71000                5              7
3          204      David  Engineering   92000                5              8
4          205       Lisa           HR   58000                4              4
5          206      james        Sales   68000                4              6
6          207       Emma  Engineering   78000                3              2
7          208     Robert    Marketing   75000                4              5
8          209     Sophia        Sales   65000                5              4
9          210    William           HR   60000                3              3

Display only Name,Deapartment,Salary columns

In [9]:
df[["Name","Department","Salary"]]

        Name   Department  Salary
0      Sarah  Engineering   85000
1    Michael        sales   62000
2  Jennifier    Marketing   71000
3      David  Engineering   92000
4       Lisa           HR   58000
5      james        Sales   68000
6       Emma  Engineering   78000
7     Robert    Marketing   75000
8     Sophia        Sales   65000
9    William           HR   60000

Display the row at 5th posistion using .iloc

In [10]:
df.iloc[4]

Employee_ID          205
Name                Lisa
Department            HR
Salary             58000
Perfomancescore        4
Yearofservice          4
Name: 4, dtype: object

Display the employee with EmployeeID 208

In [11]:
df.loc[df["Employee_ID"]==208]

   Employee_ID    Name Department  Salary  Perfomancescore  Yearofservice
7          208  Robert  Marketing   75000                4              5

Filter and display all employees from the 'Engineering' department

In [13]:
df[df['Department']=="Engineering"]

   Employee_ID   Name   Department  Salary  Perfomancescore  Yearofservice
0          201  Sarah  Engineering   85000                4              5
3          204  David  Engineering   92000                5              8
6          207   Emma  Engineering   78000                3              2

Filter and display all employees with Salary greater than 70000

In [14]:
df[df['Salary']>70000]

   Employee_ID       Name   Department  Salary  Perfomancescore  Yearofservice
0          201      Sarah  Engineering   85000                4              5
2          203  Jennifier    Marketing   71000                5              7
3          204      David  Engineering   92000                5              8
6          207       Emma  Engineering   78000                3              2
7          208     Robert    Marketing   75000                4              5

Filter and display employees from 'Sales' department with Performance Score >= 4

In [15]:
df[(df['Department']=="Sales") & (df['Perfomancescore']>=4)]

   Employee_ID    Name Department  Salary  Perfomancescore  Yearofservice
5          206   james      Sales   68000                4              6
8          209  Sophia      Sales   65000                5              4

Sort the entire DataFrame by Salary in descending order and display the top 3 highest-paid employees

In [24]:
#sorted_data=df.sort_values("Salary",ascending=False)
#sorted_data[0:3]
df.sort_values("Salary",ascending=False).head(3)

   Employee_ID   Name   Department  Salary  Perfomancescore  Yearofservice
3          204  David  Engineering   92000                5              8
0          201  Sarah  Engineering   85000                4              5
6          207   Emma  Engineering   78000                3              2

Sort by Department (ascending) and then by Salary (descending) within each department

In [26]:
df.sort_values(["Department","Salary"],ascending=[True,False])

   Employee_ID       Name   Department  Salary  Perfomancescore  Yearofservice
3          204      David  Engineering   92000                5              8
0          201      Sarah  Engineering   85000                4              5
6          207       Emma  Engineering   78000                3              2
9          210    William           HR   60000                3              3
4          205       Lisa           HR   58000                4              4
7          208     Robert    Marketing   75000                4              5
2          203  Jennifier    Marketing   71000                5              7
5          206      james        Sales   68000                4              6
8          209     Sophia        Sales   65000                5              4
1          202    Michael        sales   62000                3              3